"use client";

import { getMonthlySummary, Transaction } from "@/utils/HelperFunc";
import React, { useState } from "react";

export const SmartFinancialInsights = ({ transactions }: { transactions: Transaction[] }) => {
  const [insights, setInsights] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchInsights = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ summary: getMonthlySummary(transactions) }),
      });

      if (!res.ok) throw new Error("Failed to fetch insights");

      const data = await res.json();

      setInsights(data.insights || []);
    } catch (err) {
      console.error(err);
      setInsights(["Failed to fetch insights"]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-yellow-50 p-6 rounded-xl shadow-md  mx-auto text-gray-900">
      <h3 className="text-2xl font-bold mb-4 text-indigo-700">💡 Smart Insights</h3>
      <button
        onClick={fetchInsights}
        className="mb-4 px-5 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-all duration-200 hover:cursor-pointer"
      >
        Generate Insights
      </button>

      {loading && <p className="text-gray-500 italic">Generating insights...</p>}

      <ul className="space-y-3">
        {insights.map((i, idx) => (
          <li
            key={idx}
            className="bg-white p-4 rounded-lg shadow-sm border-l-4 border-indigo-500 hover:shadow-md transition-all duration-150"
          >
            <span className="font-medium">{`• `}</span>
            <span>{i}</span>
          </li>
        ))}
      </ul>

      {insights.length > 0 && (
        <p className="mt-4 text-gray-600 text-sm italic">
          These insights are generated by AI to help you manage your finances smarter.
        </p>
      )}
    </div>
  );
};
